version: "3.8"
services:
  store-db:
    image: postgres
    restart: always
    volumes:
      - store-pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  store-redis:
    image: redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    command:
      - redis-server
      - --requirepass ${REDIS_PASS}
volumes:
  store-pgdata:
    external: true
