post:
  summary: Create new product
  description: Create a new product, only managers or admins can create new products.
  tags:
    - Products
  operationId: createProduct
  requestBody:
    description: New product information
    required: true
    content:
      multipart/form-data:
        schema:
          $ref: './models.yaml#/CreateProductReqBody'
  responses:
    201:
      description: Product successfully created.
      content:
        application/json:
          schema:
            $ref: './models.yaml#/ProductResBody'
get:
  summary: Get products
  tags:
    - Products
  operationId: getProducts
  security: [ ]
  parameters:
    - name: sort
      in: query
      required: false
      description: Sort order (by creation time)
      schema:
        type: string
        enum: [ desc, asc ]
        default: desc
    - name: cursor
      in: query
      required: false
      description: Cursor from where the new list will start
      schema:
        type: string
        format: date-time
    - name: take
      in: query
      required: false
      description: How many products to return
      schema:
        type: integer
        minimum: 1
        maximum: 50
        default: 25
    - name: category
      in: query
      required: false
      description: Filter by a specific product category.
      schema:
        type: string
        pattern: '^[a-z][a-z_]+$'
    - name: include
      in: query
      required: false
      description: |
        Which products to include, by default will include `active` products.
      schema:
        type: string
        enum: [ all, active, inactive ]
        default: active
  responses:
    200:
      description: Successful response.
      content:
        application/json:
          schema:
            $ref: './models.yaml#/ProductsPageResBody'

