openapi: 3.1.0
info:
  title: Store API
  description: OpenAPI documentation
  version: 0.1.0
  contact:
    name: Kevin Del Castillo
    email: kevindelcastillo@ravn.co
servers:
  - url: 'http://localhost/api/v1'
security:
  - bearerAuth: [ ]
components:
  securitySchemes:
    bearerAuth:
      description: Authorization with a Json Web Token (obtained after signing in/up)
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /auth/sign-up:
    $ref: './auth/sign-up.yaml'

  /auth/sign-in:
    $ref: './auth/sign-in.yaml'

  /auth/verify-email:
    $ref: './auth/verify-email.yaml'

  /auth/resend-email:
    $ref: './auth/resend-email.yaml'

  /users:
    $ref: './users/users.yaml'

  /users/{id}:
    $ref: './users/users-by-id.yaml'

  /products/categories:
    $ref: './products/products-categories.yaml'

  /products:
    $ref: './products/products.yaml'

  /products/{id}:
    $ref: './products/products-by-id.yaml'

  /products/{id}/images:
    $ref: './products/products-by-id-images.yaml'

  /products/images/{id}:
    $ref: './products/products-images-by-id.yaml'

  /favorites:
    $ref: './favorites/favorites.yaml'

  /favorites/{id}:
    $ref: './favorites/favorites-by-id.yaml'
